import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { Plugin } from 'vite';
import glob from 'fast-glob';

export function packagePlugin(input: string, output: string, root: string = '.'): Plugin[] {
  return [
    {
      name: 'package-json-plugin',
      apply: 'build',
      enforce: 'pre',
      buildStart: async function () {
        try {
          const files = await glob('**/*', { cwd: input });
          const packageJsonPath = path.resolve(path.join(root, 'package.json'));
          const packageJsonFile = await fs.readFile(packageJsonPath, 'utf-8');
          const packageJson = JSON.parse(packageJsonFile);
          const dist = path.relative(root, output).replaceAll(path.sep, path.posix.sep);
          packageJson.exports = packageJson.exports || {};
          for (const file of files) {
            const exportPath = `./${file}`;
            const distPath = `./${path.posix.join(dist, file)}`;
            packageJson.exports[exportPath] = {
              svelte: {
                types: `${distPath}.d.ts`,
                import: distPath
              }
            };
          }
          const packageJsonOut = JSON.stringify(packageJson, null, 2);
          if (packageJsonOut != packageJsonFile) {
            await fs.writeFile(packageJsonPath, packageJsonOut);
            this.info('Updated package.json exports with Svelte components');
          }
        } catch (err) {
          this.error(`Failed to update package.json: ${err}`);
        }
      }
    },
    {
      name: 'components-index-plugin',
      apply: 'build',
      enforce: 'pre',
      buildStart: async function () {
        try {
          const files = await glob('**/*', { cwd: input });
          const indexPath = path.resolve(path.join(root, 'src', 'index.ts'));
          const indexFile = await fs.readFile(indexPath, 'utf-8');
          const exports = files.map(file => {
            const componentName = path.basename(file, '.svelte');
            return `export { default as ${componentName} } from '$components/${file}';`;
          }).join('\n');
          const indexOut = `// Auto-generated by components-index-plugin\n${exports}\n`;
          if (indexOut != indexFile) {
            await fs.writeFile(indexPath, indexOut);
            this.info('Updated index.ts with Svelte components');
          }
        } catch (err) {
          this.error(`Failed to update index.ts: ${err}`);
        }
      }
    },
    {
      name: 'svelte-package-plugin',
      apply: 'build',
      closeBundle: async function () {
        try {
          this.info('Copying Svelte components');
          const proc = spawn('svelte-package', ['--input', input, '--output', output], {
            stdio: 'pipe',
            shell: true
          });
          Promise.all([
            async () => {
              for await (const data of proc.stdout) {
                this.info(data);
              }
            },
            async () => {
              for await (const data of proc.stderr) {
                this.warn(data);
              }
            },
            new Promise((success, error) => {
              proc.once('exit', (code) => {
                if (code) error(code);
                else success(code);
              });
            })
          ]);
        } catch (err) {
          this.error(`Failed to run svelte-package: ${err}`);
        }
      }
    }
  ];
}
