# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test.yml
