# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This workflow opens and updates a pull request with a new package version
# based on code changes.

# The pull request updates the version in ButterCMS/ButterCMS.csproj,
# updates the version in readme.md, updates the changelog and creates release tags.

# For more information, see https://github.com/marketplace/actions/release-please-action
# Specs for the commit messages: https://www.conventionalcommits.org/en/v1.0.0/

name: Release Please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.7.10
        with:
          release-type: node
          package-name: release-please-action
          pull-request-title-pattern: 'chore(release): ${version}'
          pull-request-header: ':robot: Merge this PR to release a new version'
          extra-files: |
            package.json
